/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InputTest {
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SubmitButton {
    }
}
declare global {
    interface HTMLInputTestElement extends Components.InputTest, HTMLStencilElement {
    }
    var HTMLInputTestElement: {
        prototype: HTMLInputTestElement;
        new (): HTMLInputTestElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSubmitButtonElement extends Components.SubmitButton, HTMLStencilElement {
    }
    var HTMLSubmitButtonElement: {
        prototype: HTMLSubmitButtonElement;
        new (): HTMLSubmitButtonElement;
    };
    interface HTMLElementTagNameMap {
        "input-test": HTMLInputTestElement;
        "my-component": HTMLMyComponentElement;
        "submit-button": HTMLSubmitButtonElement;
    }
}
declare namespace LocalJSX {
    interface InputTest {
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SubmitButton {
        "onSubmitted"?: (event: CustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "input-test": InputTest;
        "my-component": MyComponent;
        "submit-button": SubmitButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "input-test": LocalJSX.InputTest & JSXBase.HTMLAttributes<HTMLInputTestElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "submit-button": LocalJSX.SubmitButton & JSXBase.HTMLAttributes<HTMLSubmitButtonElement>;
        }
    }
}
